//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        [Key]
        public int MaLogin { get; set; }
        public Nullable<decimal> MaNV { get; set; }
        public string Password { get; set; }
        public Nullable<int> MaNhom { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual Nhom Nhom { get; set; }
    }
}
