//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLVTEntities : DbContext
    {
        public QLVTEntities()
            : base("name=QLVTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<CT_PhatSinh> CT_PhatSinh { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Nhom> Nhoms { get; set; }
        public virtual DbSet<PhatSinh> PhatSinhs { get; set; }
        public virtual DbSet<VatTu> VatTus { get; set; }
        public virtual DbSet<MSmerge_conflict_QLVT_CN2_Login> MSmerge_conflict_QLVT_CN2_Login { get; set; }
    }
}
