//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_conflict_QLVT_CN2_Login
    {
        public int MaLogin { get; set; }
        public Nullable<decimal> MaNV { get; set; }
        public string Password { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<System.Guid> origin_datasource_id { get; set; }
    }
}
