//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhatSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhatSinh()
        {
            this.CT_PhatSinh = new HashSet<CT_PhatSinh>();
        }
    
        public string Phieu { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Loai { get; set; }
        public string HoTenKH { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<decimal> MaNV { get; set; }
        public string MaKho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PhatSinh> CT_PhatSinh { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
